spring.application.name=bilecik

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.serialization-mode=via-dto