

spring.datasource.url=jdbc:postgresql://localhost:5433/bilecik
spring.datasource.username=bilecik
spring.datasource.password=bilecik_local_dev

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE